### ISSUE TITLE
Script to update "Peak Speed" values

### ISSUE THREAD

**Issue by PatrickCleary** [transitmatters/t-performance-dash#447] opened 2023-04-05 20:06 UTC
And store them in the OverviewStats DB

Currently hardcoded [here](https://github.com/transitmatters/t-performance-dash/blob/18eec9c80300640247da1ac5a3e8a9b80b22df99/modules/speed/constants/speeds.ts#L66)

**Comment by devinmatte** [comment] 2024-09-21 23:27
Potential duplicate of #927

**Closed** 2024-09-21 23:28 UTC
Labels: nice-to-have
